[general]
import = ["/home/orlando/.config/alacritty/themes/nord.toml"]
[window]
opacity = 1

[cursor]
style = {shape = "Block", blinking = "on"}

[font]
size = 18

[font.normal]
family= "JetBrainsMono Nerd Font Mono"
