[general]
import = ["/home/orlando/.config/alacritty/themes/gruber_darker.toml"]

[env]
TERM = "xterm-256color"
[window]
opacity = 1

[cursor]
style = {shape = "Block", blinking = "on"}

[font]
size = 20

[font.normal]
family = "Iosevka Nerd Font Mono"
